on:
  push:
    branches:
      - "main"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update vite.config.js
      run: |
        sed -i '/defineConfig({/a \ \ base: "CompraFacilAccesible",' vite.config.js

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Deploy to Github Pages
      id: build-publish
      uses: bitovi/github-actions-react-to-github-pages@v1.2.4
      with:
        checkout: 'false'
        path: dist